import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
I18N_DIR = ROOT / "i18n"
OUT_FILE = ROOT / "js" / "data" / "i18n.js"

LANGS = ("en", "ru")
DOMAINS = ("ui", "characters", "weapons", "abilities")


def load_json(path):
    return json.loads(path.read_text(encoding="utf-8"))


def assert_same_keys(left, right, label):
    left_keys = set(left.keys())
    right_keys = set(right.keys())
    missing_left = right_keys - left_keys
    missing_right = left_keys - right_keys
    if missing_left or missing_right:
        if missing_left:
            print(f"[i18n] Missing {label} keys in en: {sorted(missing_left)}", file=sys.stderr)
        if missing_right:
            print(f"[i18n] Missing {label} keys in ru: {sorted(missing_right)}", file=sys.stderr)
        raise SystemExit(1)


def assert_fields(data, fields, label):
    for key, entry in data.items():
        for field in fields:
            if field not in entry:
                print(f"[i18n] Missing {label}.{field} for '{key}'", file=sys.stderr)
                raise SystemExit(1)


def dump_js(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)


def main():
    by_lang = {}
    for lang in LANGS:
        base = I18N_DIR / lang
        payload = {}
        for domain in DOMAINS:
            payload[domain] = load_json(base / f"{domain}.json")
        by_lang[lang] = payload

    ui_i18n = {lang: by_lang[lang]["ui"] for lang in LANGS}
    character_i18n = {lang: by_lang[lang]["characters"] for lang in LANGS}

    assert_same_keys(ui_i18n["en"], ui_i18n["ru"], "ui")
    assert_same_keys(character_i18n["en"], character_i18n["ru"], "characters")

    weapon_en = by_lang["en"]["weapons"]
    weapon_ru = by_lang["ru"]["weapons"]
    ability_en = by_lang["en"]["abilities"]
    ability_ru = by_lang["ru"]["abilities"]

    assert_same_keys(weapon_en, weapon_ru, "weapons")
    assert_same_keys(ability_en, ability_ru, "abilities")

    assert_fields(weapon_en, ("name", "description"), "weapons")
    assert_fields(weapon_ru, ("name", "description"), "weapons")
    assert_fields(ability_en, ("name", "description"), "abilities")
    assert_fields(ability_ru, ("name", "description"), "abilities")

    weapon_texts = {}
    for key in weapon_en.keys():
        weapon_texts[key] = {
            "name": {"en": weapon_en[key]["name"], "ru": weapon_ru[key]["name"]},
            "description": {"en": weapon_en[key]["description"], "ru": weapon_ru[key]["description"]}
        }

    ability_texts = {}
    for key in ability_en.keys():
        ability_texts[key] = {
            "name": {"en": ability_en[key]["name"], "ru": ability_ru[key]["name"]},
            "description": {"en": ability_en[key]["description"], "ru": ability_ru[key]["description"]}
        }

    parts = [
        "// This file is generated by scripts/i18n/build.py. Do not edit directly.",
        "",
        f"export const CHARACTER_I18N = {dump_js(character_i18n)};",
        "",
        f"export const WEAPON_TEXTS = {dump_js(weapon_texts)};",
        "",
        f"export const ABILITY_TEXTS = {dump_js(ability_texts)};",
        "",
        f"const UI_I18N = {dump_js(ui_i18n)};",
        "",
        "export const TRANSLATIONS = {",
        "  ui: UI_I18N,",
        "  characters: CHARACTER_I18N,",
        "  weapons: WEAPON_TEXTS,",
        "  abilities: ABILITY_TEXTS",
        "};",
        "",
        "export const I18N = {",
        "  en: {",
        "    ...UI_I18N.en,",
        "    ...(CHARACTER_I18N.en || {})",
        "  },",
        "  ru: {",
        "    ...UI_I18N.ru,",
        "    ...(CHARACTER_I18N.ru || {})",
        "  }",
        "};",
        ""
    ]

    OUT_FILE.write_text("\n".join(parts), encoding="utf-8-sig", newline="\r\n")


if __name__ == "__main__":
    main()
